# Build settings
markdown: kramdown

# Theme settings
#theme: jekyll-theme-hydeout
remote_theme: fongandrew/hydeout
paginate: 5

# Site settings
title: Soo-Jin Moon
description: "NetInfra @ Google <br> Ph.D. Carnegie Mellon University"
  #"PhD, Electrical and Computer Engineering<br/>Carnegie Mellon University"
#baseurl: "/~soojinm"
#baseurl: "/"
#~soojinm"
url: "https://soojinmoon.com"

# Social settings
email: soojin.moon91 * A T * gmail.com
scholar_user: PjCpWYsAAAAJ
cv_path: /assets/soojin-cv.pdf
profile_photo_path: /assets/images/soojin.png

google_analytics: UA-56658217-1 
